data_path: "/home/trushin/Kaggle/icr-identify-age-related-conditions/"
models_path: "models"

folds:
    n_splits: 10
    random_state: 42
    shuffle: True

method: "lightgbm"

model:
    boosting: "gbdt"
    objective: "binary"
    sigmoid: 7.0
    linear_tree: True
    linear_lambda: 0.01
    metric: "binary_logloss"
    learning_rate: 0.01
    bagging: goss
    bagging_freq: 50
    bagging_fraction: 0.7
    num_leaves: 4
    max_depth: 4
    min_data_in_leaf: 40
    feature_fraction: 0.90
    reg_alpha: 0.1
    reg_lambda: 10.
    n_jobs: -1
    is_unbalance: True
    verbose: -1
    seed: 42

train:
    num_boost_round: 500000
    early_stopping_rounds: 1000
    verbose_eval: 100

denoise: True
scaler: "RobustScaler"