data_path: "/home/trushin/Kaggle/icr-identify-age-related-conditions/"
models_path: "models"

folds:
    n_splits: 10
    random_state: 42
    shuffle: True

method: "xgboost"

model:
    tree_method: "gpu_hist"
    objective: "binary:logistic"
    eval_metric: "logloss"
    learning_rate: 0.02
    max_depth: 5
    max_leaves: 6
    colsample_bytree: 0.66
    sampling_method: "gradient_based"
    subsample: 0.4
    lambda: 1.0
    random_state: 42
    min_child_weight: 2
    grow_policy: "lossguide"

train:
    num_boost_round: 500000
    early_stopping_rounds: 1000
    verbose_eval: 100

denoise: True
scaler: "RobustScaler"